const data = [
  {
    id: 1,
    name: "Athena Weissnat",
    class:"X-A",
    Language1: 85,
    English: 90,
    Maths: 78,
    Science: 88,
    Social: 92,
  },
  {
    id: 2,
    name: "John Doe",
    
    class:"X-A",
    Language1: 75,
    English: 80,
    Maths: 92,
    Science: 85,
    Social: 88,
  },
  {
    id: 3,
    name: "Jane Smith",
    Language1: 92,
    class:"X-C",
    English: 88,
    Maths: 95,
    Science: 90,
    Social: 85,
  },
  {
    id: 4,
    name: "Michael Johnson",
    Language1: 80,
    class:"X-B",
    English: 85,
    Maths: 75,
    Science: 78,
    Social: 92,
  },
  {
    id: 5,
    name: "Emily Brown",
    class:"X-D",
    Language1: 88,
    English: 92,
    Maths: 89,
    Science: 85,
    Social: 78,
  },
  {
    id: 6,
    class:"X-A",
    name: "Daniel Williams",
    Language1: 78,
    English: 82,
    Maths: 90,
    Science: 88,
    Social: 95,
  },
  {
    id: 7,
    class:"X-A",
    name: "Olivia Davis",
    Language1: 95,
    English: 88,
    Maths: 75,
    Science: 92,
    Social: 80,
  },
  {
    id: 8,
    class:"X-E",
    name: "Ethan Miller",
    Language1: 85,
    English: 90,
    Maths: 78,
    Science: 88,
    Social: 92,
  },
  {
    id: 9,
    class:"X-D",
    name: "Sophia Wilson",
    Language1: 92,
    English: 78,
    Maths: 85,
    Science: 88,
    Social: 90,
  },
  {
    id: 10,
    class:"X-C",
    name: "Liam Moore",
    Language1: 80,
    English: 92,
    Maths: 88,
    Science: 78,
    Social: 85,
  },
];

export default data;
